### ISSUE TITLE
Changes to Pangraph Core

### ISSUE THREAD

**Issue by thisiswhereitype** [thisiswhereitype/gmlp#17]
I think module could have some changes to make it more flexible:
I propose changing `makePangraph` to
`makePangraph :: [Vertex] -> [Edge] -> Pangraph`
This simplifies the constructor, instead performing verification on `Pangraph` later.
`verifyGraph :: Pangraph -> Either (GraphErr) (VerifiedPangraph)`
Where VerifiedPangraph is maybe a `newtype` wrapper.
I suppose this also allows Pangraph to express malformed graphs.

**Comment by snowleopard** [comment]
> I suppose this also allows Pangraph to express malformed graphs.

Why would you want this? Malformed graphs are not graphs, so they are outside the scope of the project.

> This simplifies the constructor

I think what you propose in fact complicates things for the user. Instead of calling one function, dealing with one graph data type, and handling one error, they will need to call two functions, deal with two data types, and still handle one error. I see no simplification.

If you don't like handling `Maybe` when you are doing quick prototyping, you could add an unsafe version of the constructor:
```haskell
unsafeMakePangraph :: [Vertex] -> [Edge] -> Pangraph
unsafeMakePangraph vs es = fromMaybe (error "Oh no, it's not a graph!") (makePangraph vs es)
```

This adds only one function into the API, so it's more lightweight than your proposal, however note that this could still be easily done in user code instead.

**Comment by thisiswhereitype** [comment]
I agree with what you have said, perhaps there is need for an unsafe version.
